apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hanu
spec:
  entrypoint: main
  serviceAccountName: argo
  arguments:
    parameters:
      - name: branch
        value: main
      - name: dockerRepo
        value: hanub.jfrog.io/default-docker/go-api:2.0
  templates:
  - name: clone
    steps:
    - - name: clone
        templateRef:
          name: clone
          template: clone
        
    - - name: deps
        templateRef:
          name: deps
          template: deps
    - - name: build
        templateRef:
          name: build
          template: build
    - - name: docker-build
        templateRef:
          name: docker-build
          template: docker-build
        
